#!/bin/bash

# This script will add public trackers to all active torrents

# Get transmission credentials
auth=username:password #  <------Change
host=localhost # <---- This should be fine if script is on transmission computer

add_trackers () {
# Public Trackers Site 1
# https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt
    torrent_hash=$1
 for base_url in https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt ; do
    echo -e "\e[1m"
    echo "URL for ${base_url}"
    echo -e "Adding trackers for \e[92m $id of $last \033[38;5;92m Tracker Set 1 \e[91m $torrent_name..."
sleep 2
echo -en "\e[0m"
    echo -e "\e[2m\e[92m"
for tracker in $(curl -# "${base_url}") ; do
    echo -en "\e[0m"
    echo -ne "\e[93m*\e[0m ${tracker}..."
    result=$(transmission-remote "$host" --auth="$auth" --torrent "${torrent_hash}" -td "${tracker}" 2>&1)
    if echo "$result" | grep -q 'success'; then
        echo -e '\e[92m done.'
    elif echo "$result" | grep -q 'error setting announce list'; then
        echo -e '\e[33m exists.'
    else
        echo -e '\e[91m failed.'
    fi
    echo -en "\e[0m"
 done
#sleep 1
done
#--------------------------------------
# Public Trackers Site 2
# https://newtrackon.com/api/stable
torrent_hash=$1
 for base_url in https://newtrackon.com/api/stable ; do
    echo -e "\e[1m"
    echo "URL for ${base_url}"
    echo -e "Adding trackers for \e[92m $id of $last \033[38;5;92m Tracker Set 2 \e[91m $torrent_name..."
sleep 2
    echo -en "\e[0m"
    echo -e "\e[2m\e[92m"
for tracker in $(curl -# "${base_url}") ; do
    echo -en "\e[0m"
    echo -ne "\e[93m*\e[0m ${tracker}..."
    result=$(transmission-remote "$host" --auth="$auth" --torrent "${torrent_hash}" -td "${tracker}" 2>&1)
    if echo "$result" | grep -q 'success'; then
        echo -e '\e[92m done.'
    elif echo "$result" | grep -q 'error setting announce list'; then
        echo -e '\e[33m exists.'
    else
        echo -e '\e[91m failed.'
    fi
    echo -en "\e[0m"
 done
#sleep 1
done

#--------------------------------------
# Public Trackers Site 3
# https://trackerslist.com/all.txt
torrent_hash=$1
 for base_url in https://trackerslist.com/all.txt ; do
    echo -e "\e[1m"
    echo "URL for ${base_url}"
    echo -e "Adding trackers for \e[92m $id of $last \033[38;5;92m Tracker Set 3 \e[91m $torrent_name..."
sleep 2
echo -en "\e[0m"
    echo -e "\e[2m\e[92m"
for tracker in $(curl -# "${base_url}") ; do
    echo -en "\e[0m"
    echo -ne "\e[93m*\e[0m ${tracker}..."
    result=$(transmission-remote "$host" --auth="$auth" --torrent "${torrent_hash}" -td "${tracker}" 2>&1)
    if echo "$result" | grep -q 'success'; then
        echo -e '\e[92m done.'
    elif echo "$result" | grep -q 'error setting announce list'; then
        echo -e '\e[33m exists.'
    else
        echo -e '\e[91m failed.'
    fi
    echo -en "\e[0m"
 done
done

}

# Get list of active torrents
ids="$(transmission-remote "$host" --auth="$auth" --list | grep -vE 'Seeding|Stopped|Finished' | grep '^ ' | awk '{ print $1 }' | tail -n +2)"
last="$(printf "%b\n" $ids | wc -l)"

for id in $ids ; do
    hash="$(transmission-remote "$host" --auth="$auth"  --torrent "$id" --info | grep '^  Hash: ' | awk '{ print $2 }')"
    torrent_name="$(transmission-remote "$host" --auth="$auth"  --torrent "$id" --info | grep '^  Name: ' |cut -c 9-)"
    add_trackers "$hash"
done
